services:
  postgres:
    image: postgres:17
    container_name: sgah-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: sgah
      POSTGRES_PASSWORD: sgah
      POSTGRES_DB: sgah_db
    ports:
      - "5432:5432"
    volumes:
      - sgah_postgres_data:/var/lib/postgresql/data

volumes:
  sgah_postgres_data:
